server:
  port: 8081
  servlet:
    context-path: /api
spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/bookingClone"
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update # create, create-drop, update, validate, none
  sql:
    init:
      mode: never
jwt:
  signerKey: "ISaeBKjUzdPg8OWFRm5Cq42I4XZlefm2s/6nxKOpC+j8aHQ16dYfX6ON6AAfu3Te"
  valid-duration: 60
  refreshable-duration: 120

file:
  upload-dir: "D:/booking-hotel/uploads"
  upload-post: "thumbnail_post"
  upload-user: "user"
  upload-posts: "posts"
